name: Publish Documentation
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Choose a tag'
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Setup git
        uses: ./.github/actions/setup-git
      - name: Generate Dokka Documentation
        run: ./gradlew dokkaGenerateHtml

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/dokka/html
          clean: true
